version: "3"

services:
  phoenix:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: phodash_prod
      PGHOST: db
      PGPORT: 5432
      DATABASE_URL: ecto://postgres:postgres@db/phodash_prod
      SECRET_KEY_BASE: yfS/m/JQxtNBDIPn2F9MCnArcbmYBenDBs7fdUj0/XAKdVNmMkTRGmkk7E6Ao1bD
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./_pgdata:/var/lib/postgresql/data

  